title : API Voice

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: api-voice
destination: api-voice

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://apivoice.com

BASE_PATH : http://apivoice.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
